Fixed the TypeError in Python 3.5
Fixed the 
TypeError: memoryview: a bytes-like object is required, not 'str'
in Python 3.5.

May not work or needs to be tested in 2.x .